#!/bin/bash

echo "Build boot jars"
./gradlew :router:bootJar
./gradlew :server:bootJar
./gradlew :reconciler:bootJar

echo "Copy Jars"
scp router/build/libs/router-0.0.1-SNAPSHOT.jar aws-zuul-edge:/home/ubuntu/router.jar
scp server/build/libs/server-0.0.1-SNAPSHOT.jar aws-zuul-service:/home/ubuntu/server.jar
scp reconciler/build/libs/reconciler-0.0.1-SNAPSHOT.jar aws-zuul-reconciler:/home/ubuntu/reconciler.jar
scp server/build/libs/server-0.0.1-SNAPSHOT.jar aws-zuul-reconciler:/home/ubuntu/server.jar

echo "Restart services"
ssh aws-zuul-edge 'pkill -f "java -jar"'
ssh aws-zuul-edge 'java -jar router.jar &> router.log &'

ssh aws-zuul-service 'pkill -f "java -jar"'
ssh aws-zuul-service 'java -jar server.jar &> server.log &'

ssh aws-zuul-reconciler 'pkill -f "java -jar"'
ssh aws-zuul-reconciler 'java -jar server.jar &> server.log &'
ssh aws-zuul-reconciler 'java -jar reconciler.jar &> reconciler.log &'
